### PR TITLE
Ubuntu compatibility

### PR DESCRIPTION
**Pull request by anselanza**
Just a start on basic Ubuntu compatibility.

Debugging not quite working properly yet when trying to step through - see screenshot below.

screen shot 2018-01-05 at 10 29 55 3

### CODE REVIEW

**Comment by anselanza** [comment]
Hmmm checks failing... think it has something to do with similar issues like https://github.com/chaijs/chai/issues/1075 - nothing to worry about?

**Comment by hiroMTB** [comment]
Thanks!
Is this because we don't have .appveyor.yml and .travis.yml files?

**Comment by hiroMTB** [comment]
We might need to change entire directory structure to enable ci feature.
Normally oF app/addon repo has following structure.
- ofxSomething
  - src
  - libs
  - ofxSomethingExample
    - project files
    - src
  - .appbeyor.yml
  - .travis.yml

and this repo is 
- vscode_oF
  - project files
  - .appbeyor.yml
  - .travis.yml

 I will test this on dev branch.

**Comment by anselanza** [comment]
Hmmm ok makes sense. Let me know if that works. Meanwhile going to try to get debugging (stepping) work properly if possible.

**Comment by anselanza** [comment]
Wow, the debugging errors are more tricky than I thought.

So far, specifically with vscode:
* https://github.com/Microsoft/vscode-cpptools/issues/1022
* https://github.com/Microsoft/vscode-cpptools/issues/811

And related context but not specific to vscode:
* https://sourceware.org/ml/gdb/2016-01/msg00016.html
* http://www.squaregoldfish.co.uk/2013/01/06/debugging-in-ubuntu-12-10-missing-file-syscall-template-s/

**Comment by anselanza** [comment]
`apt-get source glibc-source` at least gets me the missing file (`./sysdeps/unix/syscall-template.S`) but no idea how to (sym?)link it to the place the debugger expects to find it.

As I understand it, the "error" can be safely ignored but due to the way vscode keeps popping up the dialogue box it makes debugging essentially useless.

Being able to step through code is exactly why I would want to use vscode (over just a plain text editor) on Linux which is why I think it's an important issue to fix (or work around).

**Comment by hiroMTB** [comment]
Thanks for this input.

About ci system, now it works of on dev branch for windows and linux.
OSX test fails because of link error. Looks like  [oF's libopenFrameworksDebug.a file](http://ci.openframeworks.cc/openFrameworks_libs/osx) is broken but will be fixed soon I think.
https://travis-ci.org/hiroMTB/vscode_oF
https://ci.appveyor.com/project/hiroMTB/vscode-of

And about debugger on Linux, I will check your link later.
I plan to install Ubuntu but probably next month.

**Comment by anselanza** [comment]
Intellisense errors appear to be fixed now, by adding a bunch of include paths.

**Comment by anselanza** [comment]
The last change appears to have made debugging work, too!

**Comment by hiroMTB** [comment]
I didn't checked but merged because it won't conflict OSX settings. 
Super thanks!

**Pull request merged**
